export const MUTATION = {
    USER: {
        SET: 'SET_USER',
    },
    PRODUCTS: {
        SET : 'SET_PRODUCTS',
        TOGGLE: 'TOGGLE_PRODUCT',
        CLEAR_CHECKED: 'CLEAR_CHECKED_PRODUCT',
        CLEAR_ALL_CHECKED: 'CLEAR_ALL_CHECKED_PRODUCT',
    },
    QUESTIONS:{
        SET: 'SET_QUESTIONS',
        SELECT: 'SELECT_QUESTIONS'
    }
}
