export const MUTATION = {
    USER: {
        SET: 'SET_USER',
    },
    PRODUCTS: {
        SET: 'SET_PRODUCTS',
        TOGGLE: 'TOGGLE_PRODUCT',

        SELECT_OPERATION: 'SELECT_OPERATION_PRODUCT',
        SELECT_OPERATION_GROUP: 'SELECT_OPERATION_GROUP_PRODUCT',
        SELECT_OPRATION_ALL: 'SELECT_OPERATION_ALL_PRODUCT',
    },
    QUESTIONS: {
        SET: 'SET_QUESTIONS',
        SELECT: 'SELECT_QUESTIONS'
    },
    SETTINGS: {
        SET: 'SET_SETTINGS',
    },
    APP: {
        SET_HTTP: 'SET_HTTP_APP',
        SET_HTTP_IGNORE: 'SET_HTTP_IGNORE_APP',
    }
}
